
name: Deploy Frontend

on:

  push:

    branches: [main]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          key: ${{ secrets.SSH_KEY }}

          port: ${{ secrets.PORT }}

          command_timeout: 10m

          script: |

            export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && cd /var/www/frontend/app && git reset --hard && git pull origin main && npm ci && npm run build && rm -rf /var/www/frontend/dist/* && cp -r dist/* /var/www/frontend/dist/ && nginx -s reload

